PREFIX="/home/binni/miniconda3"
CONDARC="/home/binni/.condarc"

rule all:
    input: PREFIX
    shell: "export PATH=\"$(realpath {input}/bin):$PATH\";conda install argcomplete"

rule copy_condarc:
    output: CONDARC
    shell: "ln -s /home/binni/Programming/MyScripts/dotfiles/.condarc {output};touch {output}"

rule get_latest:
    input: CONDARC
    output: "Miniconda.txt"
    shell: "python2 GetLatestMiniconda.py > {output}"

rule download_latest:
    input: rules.get_latest.output
    output: "miniconda.sh"
    shell: "wget $(cat {input}) -O {output};touch {output}"

rule install_conda:
    input: rules.download_latest.output
    output: dir=PREFIX
    shell: "bash {input} -b -p {output}"

rule clean:
    """clean up files"""
    shell: "rm -rf {rules.copy_condarc.output} {rules.install_conda.output} {rules.download_latest.output} {rules.get_latest.output}"
